
CREATE TABLE HARE_TYPES (
    `SEQ` INT NOT NULL,
    `HARE_TYPE` INT NOT NULL,
    `HARE_TYPE_NAME` VARCHAR(25) NOT NULL,
    PRIMARY KEY (`HARE_TYPE`),
    UNIQUE KEY (`SEQ`),
    UNIQUE KEY (`HARE_TYPE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO HARE_TYPES VALUES(10, 1<<0, 'True');
INSERT INTO HARE_TYPES VALUES(20, 1<<1, 'Trail');
INSERT INTO HARE_TYPES VALUES(30, 1<<2, 'Hyper');
INSERT INTO HARE_TYPES VALUES(40, 1<<3, 'Food');
INSERT INTO HARE_TYPES VALUES(50, 1<<4, 'Beer');
INSERT INTO HARE_TYPES VALUES(60, 1<<5, 'Trivia');

ALTER TABLE HARINGS ADD `HARE_TYPE` INT;

UPDATE HARINGS SET HARE_TYPE=1<<2 WHERE HARINGS_HASH_KY IN (
    SELECT HASH_KY FROM HASHES WHERE HASH_TYPE=2);

UPDATE HARINGS SET HARE_TYPE=1<<0 WHERE HARINGS_HASH_KY IN (
    SELECT HASH_KY FROM HASHES WHERE HASH_TYPE=1);

ALTER TABLE HARINGS CHANGE HARE_TYPE HARE_TYPE INT NOT NULL;

ALTER TABLE HASH_TYPES ADD HARE_TYPE_MASK INT;

UPDATE HASH_TYPES SET HARE_TYPE_MASK = 1<<0 WHERE HASH_TYPE_NAME='Regular';
UPDATE HASH_TYPES SET HARE_TYPE_MASK = 1<<2 WHERE HASH_TYPE_NAME='Hyper';
UPDATE HASH_TYPES SET HARE_TYPE_MASK = 1<<1 | 1<<5 WHERE HASH_TYPE_NAME='Trivia';

ALTER TABLE HASH_TYPES CHANGE HARE_TYPE_MASK HARE_TYPE_MASK INT NOT NULL;

ALTER TABLE KENNELS ADD HARE_TYPE_MASK INT;

UPDATE KENNELS SET HARE_TYPE_MASK = 1<<0 | 1<<2;

UPDATE KENNELS SET HARE_TYPE_MASK = 1<<0 | 1<<1 | 1<<2 | 1<<5 WHERE KENNEL_ABBREVIATION='MVH3';

ALTER TABLE KENNELS CHANGE HARE_TYPE_MASK HARE_TYPE_MASK INT NOT NULL;

ALTER TABLE HARE_TYPES ADD CHART_COLOR VARCHAR(20);

UPDATE HARE_TYPES SET CHART_COLOR='255, 255, 0' WHERE HARE_TYPE_NAME = 'True';
UPDATE HARE_TYPES SET CHART_COLOR='255, 128, 0' WHERE HARE_TYPE_NAME = 'Trail';
UPDATE HARE_TYPES SET CHART_COLOR='128, 255, 0' WHERE HARE_TYPE_NAME = 'Hyper';
UPDATE HARE_TYPES SET CHART_COLOR='128, 128, 0' WHERE HARE_TYPE_NAME = 'Food';
UPDATE HARE_TYPES SET CHART_COLOR='0, 255, 0' WHERE HARE_TYPE_NAME = 'Beer';
UPDATE HARE_TYPES SET CHART_COLOR='0, 128, 0' WHERE HARE_TYPE_NAME = 'Trivia';

ALTER TABLE HARE_TYPES CHANGE CHART_COLOR CHART_COLOR VARCHAR(20) NOT NULL;
