CREATE TABLE HASH_TYPES (
    `SEQ` INT NOT NULL,
    `HASH_TYPE` INT NOT NULL,
    `HASH_TYPE_NAME` VARCHAR(25) NOT NULL,
    PRIMARY KEY (`HASH_TYPE`),
    UNIQUE KEY (`SEQ`),
    UNIQUE KEY (`HASH_TYPE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO HASH_TYPES VALUES(10, 1<<0, 'Regular');
INSERT INTO HASH_TYPES VALUES(20, 1<<1, 'Hyper');
INSERT INTO HASH_TYPES VALUES(30, 1<<2, 'Trivia');

ALTER TABLE HASHES ADD `HASH_TYPE` INT;

UPDATE HASHES SET HASH_TYPE=1<<0 WHERE IS_HYPER=0;
UPDATE HASHES SET HASH_TYPE=1<<1 WHERE IS_HYPER=1;

ALTER TABLE KENNELS ADD HASH_TYPE_MASK INT;

UPDATE KENNELS SET HASH_TYPE_MASK = 1<<0 | 1<<1;

UPDATE KENNELS SET HASH_TYPE_MASK = 1<<0 | 1<<1 | 1<<2 WHERE KENNEL_ABBREVIATION='MVH3';

ALTER TABLE KENNELS CHANGE HASH_TYPE_MASK HASH_TYPE_MASK INT NOT NULL;

ALTER TABLE HASHES DROP IS_HYPER;
