
CREATE TABLE HARE_TYPES (
    `SEQ` INT NOT NULL,
    `HARE_TYPE` BIT(64) NOT NULL,
    `HARE_TYPE_NAME` VARCHAR(25) NOT NULL,
    PRIMARY KEY (`HARE_TYPE`),
    UNIQUE KEY (`SEQ`),
    UNIQUE KEY (`HARE_TYPE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO HARE_TYPES VALUES(10, 1<<0, 'True');
INSERT INTO HARE_TYPES VALUES(20, 1<<1, 'Trail');
INSERT INTO HARE_TYPES VALUES(30, 1<<2, 'Hyper');
INSERT INTO HARE_TYPES VALUES(40, 1<<3, 'Food');
INSERT INTO HARE_TYPES VALUES(50, 1<<4, 'Beer');

ALTER TABLE HARINGS ADD `HARE_TYPE` BIT(64);

UPDATE HARINGS SET HARE_TYPE=1<<2 WHERE HARINGS_HASH_KY IN (
    SELECT HASH_KY FROM HASHES WHERE HASH_TYPE=2);

UPDATE HARINGS SET HARE_TYPE=1<<0 WHERE HARINGS_HASH_KY IN (
    SELECT HASH_KY FROM HASHES WHERE HASH_TYPE=1);

ALTER TABLE HARINGS ADD CONSTRAINT `HARE_TYPE` FOREIGN KEY (`HARE_TYPE`) REFERENCES `HARE_TYPES` (`HARE_TYPE`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE HARINGS CHANGE HARE_TYPE HARE_TYPE BIT(64) NOT NULL;

ALTER TABLE HASH_TYPES ADD HARE_TYPE_MASK BIT(64);

UPDATE HASH_TYPES SET HARE_TYPE_MASK = 1<<0 | 1<<1;

ALTER TABLE HASH_TYPES CHANGE HARE_TYPE_MASK HARE_TYPE_MASK BIT(64) NOT NULL;
