CREATE TABLE `HARINGS` (
  `HARINGS_HASHER_KY` int(11) NOT NULL,
  `HARINGS_HASH_KY` int(11) NOT NULL,
  KEY `HASHER_KY_idx` (`HARINGS_HASHER_KY`),
  KEY `HASH_KY_idx` (`HARINGS_HASH_KY`),
  CONSTRAINT `HARINGS_HASHER_KY` FOREIGN KEY (`HARINGS_HASHER_KY`) REFERENCES `HASHERS` (`HASHER_KY`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `HARINGS_HASH_KY` FOREIGN KEY (`HARINGS_HASH_KY`) REFERENCES `HASHES` (`HASH_KY`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
