CREATE TABLE `HASHES` (
  `HASH_KY` int(11) NOT NULL AUTO_INCREMENT,
  `KENNEL_KY` int(11) NOT NULL,
  `KENNEL_EVENT_NUMBER` varchar(45) NOT NULL,
  `EVENT_DATE` datetime NOT NULL,
  `EVENT_LOCATION` varchar(45) DEFAULT NULL,
  `EVENT_CITY` varchar(45) DEFAULT NULL,
  `EVENT_STATE` varchar(45) DEFAULT NULL,
  `SPECIAL_EVENT_DESCRIPTION` varchar(135) DEFAULT NULL,
  `VIRGIN_COUNT` int(10) unsigned zerofill DEFAULT '0000000000',
  `IS_HYPER` int(10) unsigned zerofill DEFAULT '0000000000',
  PRIMARY KEY (`HASH_KY`),
  UNIQUE KEY `HASH_KY_UNIQUE` (`HASH_KY`)
) ENGINE=InnoDB AUTO_INCREMENT=1008 DEFAULT CHARSET=utf8;
