CREATE TABLE `HASHES_TAG_JUNCTION` (
  `HASHES_TAG_JUNCTION_PKY` INT NOT NULL AUTO_INCREMENT,
  `HASHES_KY` INT NOT NULL,
  `HASHES_TAGS_KY` INT NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATION_DTTM` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFICATION_DTTM` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`HASHES_TAG_JUNCTION_PKY`));
