CREATE TABLE `HASHINGS` (
  `HASHER_KY` int(11) NOT NULL,
  `HASH_KY` int(11) NOT NULL,
  KEY `HASHER_KY_idx` (`HASHER_KY`),
  KEY `HASH_KY_idx` (`HASH_KY`),
  CONSTRAINT `HASHER_KY` FOREIGN KEY (`HASHER_KY`) REFERENCES `HASHERS` (`HASHER_KY`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `HASH_KY` FOREIGN KEY (`HASH_KY`) REFERENCES `HASHES` (`HASH_KY`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
