CREATE TABLE `HASHES_TAGS` (
  `HASHES_TAGS_KY` INT NOT NULL AUTO_INCREMENT,
  `TAG_TEXT` varchar(45) NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATION_DTTM` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFICATION_DTTM` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`HASHES_TAGS_KY`)
);
