
CREATE TABLE `LEGACY_HASHINGS` (
  `HASHER_KY` int(11) NOT NULL,
  `KENNEL_KY` int(11) NOT NULL,
  `LEGACY_HASHINGS_COUNT` int(8) NOT NULL,
  KEY `HASHER_KY_idx` (`HASHER_KY`),
  CONSTRAINT `LEGACY_HASHINGS_HASHER_KY` FOREIGN KEY (`HASHER_KY`) REFERENCES `HASHERS` (`HASHER_KY`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
