CREATE TABLE `KENNELS` (
  `KENNEL_KY` int(11) NOT NULL AUTO_INCREMENT,
  `KENNEL_NAME` varchar(90) NOT NULL,
  `KENNEL_DESCRIPTION` varchar(90) DEFAULT NULL,
  `KENNEL_ABBREVIATION` varchar(45) DEFAULT NULL,
  `IN_RECORD_KEEPING` int(11) DEFAULT '0',
  PRIMARY KEY (`KENNEL_KY`)
) ENGINE=InnoDB AUTO_INCREMENT=105 DEFAULT CHARSET=utf8;
