CREATE TABLE `AUDIT` (
  `AUDIT_KY` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) DEFAULT NULL,
  `AUDIT_TIME` datetime DEFAULT NULL,
  `ACTION_TYPE` varchar(45) DEFAULT NULL,
  `ACTION_DESCRIPTION` varchar(270) DEFAULT NULL,
  `IP_ADDR` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`AUDIT_KY`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=latin1;
