ALTER TABLE `sch4_database`.`HASHES` 
ADD COLUMN `STREET_NUMBER` VARCHAR(45) NULL AFTER `IS_HYPER`,
ADD COLUMN `ROUTE` VARCHAR(45) NULL AFTER `STREET_NUMBER`,
ADD COLUMN `COUNTY` VARCHAR(45) NULL AFTER `ROUTE`,
ADD COLUMN `POSTAL_CODE` VARCHAR(45) NULL AFTER `COUNTY`,
ADD COLUMN `NEIGHBORHOOD` VARCHAR(45) NULL AFTER `POSTAL_CODE`,
ADD COLUMN `COUNTRY` VARCHAR(45) NULL AFTER `NEIGHBORHOOD`,
ADD COLUMN `FORMATTED_ADDRESS` VARCHAR(90) NULL AFTER `COUNTRY`,
ADD COLUMN `PLACE_ID` VARCHAR(135) NULL AFTER `FORMATTED_ADDRESS`,
ADD COLUMN `LAT` DECIMAL(10,8) NULL AFTER `PLACE_ID`,
ADD COLUMN `LNG` DECIMAL(11,8) NULL AFTER `LAT`;
