<?php


define("HARING_PERCENTAGES_HYPERS_VS_ALL","SELECT
	HASHERS.HASHER_NAME,
    HASHERS.HASHER_KY,
    ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT,
    HYPER_HARING_COUNT_TEMP_TABLE.HYPER_HARING_COUNT,
    ((HYPER_HARING_COUNT_TEMP_TABLE.HYPER_HARING_COUNT / ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT) * 100) AS HYPER_HARINGS_PERCENTAGE,
    (((ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT - HYPER_HARING_COUNT_TEMP_TABLE.HYPER_HARING_COUNT) / ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT) * 100) AS NON_HYPER_HARINGS_PERCENTAGE
FROM
	HASHERS
JOIN (SELECT
		HARINGS.HARINGS_HASHER_KY AS HARINGS_HASHER_KY,
		COUNT(HARINGS.HARINGS_HASHER_KY) AS ALL_HARING_COUNT
        FROM
            HARINGS
        GROUP BY HARINGS.HARINGS_HASHER_KY) ALL_HARING_COUNT_TEMP_TABLE ON (HASHERS.HASHER_KY = ALL_HARING_COUNT_TEMP_TABLE.HARINGS_HASHER_KY)
JOIN (SELECT
		HARINGS.HARINGS_HASHER_KY AS HARINGS_HASHER_KY,
		COUNT(HARINGS.HARINGS_HASHER_KY) AS HYPER_HARING_COUNT
        FROM
            HARINGS JOIN HASHES on HARINGS.HARINGS_HASH_KY = HASHES.HASH_KY WHERE HASHES.IS_HYPER = 1
        GROUP BY HARINGS.HARINGS_HASHER_KY) HYPER_HARING_COUNT_TEMP_TABLE ON (HASHERS.HASHER_KY = HYPER_HARING_COUNT_TEMP_TABLE.HARINGS_HASHER_KY)
ORDER BY (((ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT - HYPER_HARING_COUNT_TEMP_TABLE.HYPER_HARING_COUNT) / ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT) * 100) DESC
");


define("HASHER_COUNTS_BY_YEAR","SELECT HASHERS.HASHER_NAME AS HASHER_NAME,count(*) AS THE_COUNT
  FROM (
    HASHERS
      JOIN HASHINGS ON(HASHERS.HASHER_KY = HASHINGS.HASHER_KY))
      JOIN HASHES ON HASHINGS.HASH_KY = HASHES.HASH_KY
  WHERE
    YEAR(HASHES.EVENT_DATE) = ?
  GROUP BY hashers.HASHER_NAME ORDER BY THE_COUNT DESC"
);


define("TOTAL_HARE_COUNTS_BY_YEAR","SELECT HASHERS.HASHER_NAME AS HASHER_NAME,count(*) AS THE_COUNT
FROM (
	HASHERS
    JOIN HARINGS ON(HASHERS.HASHER_KY = HARINGS.HARINGS_HASHER_KY))
    JOIN HASHES ON HARINGS.HARINGS_HASH_KY = HASHES.HASH_KY
WHERE
	YEAR(HASHES.EVENT_DATE) = ?
GROUP BY HASHERS.HASHER_NAME ORDER BY THE_COUNT DESC");

define("HYPER_HARE_COUNTS_BY_YEAR","SELECT HASHERS.HASHER_NAME AS HASHER_NAME,count(*) AS THE_COUNT
FROM (
	HASHERS
    JOIN HARINGS ON(HASHERS.HASHER_KY = HARINGS.HARINGS_HASHER_KY))
    JOIN HASHES ON HARINGS.HARINGS_HASH_KY = HASHES.HASH_KY
WHERE
	YEAR(HASHES.EVENT_DATE) = ? AND
    HASHES.IS_HYPER = 1
GROUP BY HASHERS.HASHER_NAME ORDER BY THE_COUNT DESC");

define("NONHYPER_HARE_COUNTS_BY_YEAR","SELECT HASHERS.HASHER_NAME AS HASHER_NAME,count(*) AS THE_COUNT
FROM (
	HASHERS
    JOIN HARINGS ON(HASHERS.HASHER_KY = HARINGS.HARINGS_HASHER_KY))
    JOIN HASHES ON HARINGS.HARINGS_HASH_KY = HASHES.HASH_KY
WHERE
	YEAR(HASHES.EVENT_DATE) = ? AND
    HASHES.IS_HYPER = 0
GROUP BY HASHERS.HASHER_NAME ORDER BY THE_COUNT DESC");

define ("SELECT_HASHERS_VIRGIN_HASH","SELECT
	HASHES.HASH_KY,
    KENNEL_KY,
    KENNEL_EVENT_NUMBER,
    EVENT_DATE,
    EVENT_LOCATION,
    EVENT_CITY,
    EVENT_STATE,
    SPECIAL_EVENT_DESCRIPTION,
    VIRGIN_COUNT,
    IS_HYPER,
    DATE_FORMAT(EVENT_DATE,\"%m/%d/%Y\") AS EVENT_DATE_FORMATTED,
	FLOOR(DATEDIFF(CURDATE(),EVENT_DATE)/365) YEARS_SINCE_EVENT,
    FLOOR((DATEDIFF(CURDATE(),EVENT_DATE)/365 - FLOOR(DATEDIFF(CURDATE(),EVENT_DATE)/365))* 12) MONTHS_SINCE_EVENT,
    CEILING((((DATEDIFF(CURDATE(),EVENT_DATE)/365 - FLOOR(DATEDIFF(CURDATE(),EVENT_DATE)/365))* 12)
            - FLOOR((DATEDIFF(CURDATE(),EVENT_DATE)/365 - FLOOR(DATEDIFF(CURDATE(),EVENT_DATE)/365))* 12))* 30) DAYS_SINCE_EVENT
FROM
	HASHES
    JOIN HASHINGS ON HASHES.HASH_KY = HASHINGS.HASH_KY
WHERE
	HASHINGS.HASHER_KY = ? AND
    HASHES.KENNEL_KY = ?
ORDER BY
	HASHES.EVENT_DATE ASC
LIMIT 1");

define ("SELECT_HASHERS_MOST_RECENT_HASH","SELECT
	HASHES.HASH_KY,
    KENNEL_KY,
    KENNEL_EVENT_NUMBER,
    EVENT_DATE,
    EVENT_LOCATION,
    EVENT_CITY,
    EVENT_STATE,
    SPECIAL_EVENT_DESCRIPTION,
    VIRGIN_COUNT,
    IS_HYPER,
    DATE_FORMAT(EVENT_DATE,\"%m/%d/%Y\") AS EVENT_DATE_FORMATTED,
	FLOOR(DATEDIFF(CURDATE(),EVENT_DATE)/365) YEARS_SINCE_EVENT,
    FLOOR((DATEDIFF(CURDATE(),EVENT_DATE)/365 - FLOOR(DATEDIFF(CURDATE(),EVENT_DATE)/365))* 12) MONTHS_SINCE_EVENT,
    CEILING((((DATEDIFF(CURDATE(),EVENT_DATE)/365 - FLOOR(DATEDIFF(CURDATE(),EVENT_DATE)/365))* 12)
            - FLOOR((DATEDIFF(CURDATE(),EVENT_DATE)/365 - FLOOR(DATEDIFF(CURDATE(),EVENT_DATE)/365))* 12))* 30) DAYS_SINCE_EVENT
FROM
	HASHES
    JOIN HASHINGS ON HASHES.HASH_KY = HASHINGS.HASH_KY
WHERE
	HASHINGS.HASHER_KY = ? AND
    HASHES.KENNEL_KY = ?
ORDER BY
	HASHES.EVENT_DATE DESC
LIMIT 1");
