<?php


define("HARING_PERCENTAGES_HYPERS_VS_ALL","SELECT
	HASHERS.HASHER_NAME,
    HASHERS.HASHER_KY,
    ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT,
    HYPER_HARING_COUNT_TEMP_TABLE.HYPER_HARING_COUNT,
    ((HYPER_HARING_COUNT_TEMP_TABLE.HYPER_HARING_COUNT / ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT) * 100) AS HYPER_HARINGS_PERCENTAGE,
    (((ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT - HYPER_HARING_COUNT_TEMP_TABLE.HYPER_HARING_COUNT) / ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT) * 100) AS NON_HYPER_HARINGS_PERCENTAGE
FROM
	HASHERS
JOIN (SELECT
		HARINGS.HARINGS_HASHER_KY AS HARINGS_HASHER_KY,
		COUNT(HARINGS.HARINGS_HASHER_KY) AS ALL_HARING_COUNT
        FROM
            HARINGS
        GROUP BY HARINGS.HARINGS_HASHER_KY) ALL_HARING_COUNT_TEMP_TABLE ON (HASHERS.HASHER_KY = ALL_HARING_COUNT_TEMP_TABLE.HARINGS_HASHER_KY)
JOIN (SELECT
		HARINGS.HARINGS_HASHER_KY AS HARINGS_HASHER_KY,
		COUNT(HARINGS.HARINGS_HASHER_KY) AS HYPER_HARING_COUNT
        FROM
            HARINGS JOIN HASHES on HARINGS.HARINGS_HASH_KY = HASHES.HASH_KY WHERE HASHES.IS_HYPER = 1
        GROUP BY HARINGS.HARINGS_HASHER_KY) HYPER_HARING_COUNT_TEMP_TABLE ON (HASHERS.HASHER_KY = HYPER_HARING_COUNT_TEMP_TABLE.HARINGS_HASHER_KY)
ORDER BY (((ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT - HYPER_HARING_COUNT_TEMP_TABLE.HYPER_HARING_COUNT) / ALL_HARING_COUNT_TEMP_TABLE.ALL_HARING_COUNT) * 100) DESC
");
